### ISSUE TITLE
部分汉化不完全

### ISSUE THREAD

**Issue by YaeSakuraQvQ** [Yukari316/ExplorerPatcher_zh-CN#8]
win11下开启`开始菜单`-`开始菜单风格:`-`Windows 10`中部分文本汉化不完全(如下图)
<img width="210" alt="image" src="https://github.com/Yukari316/ExplorerPatcher_zh-CN/assets/87939280/c9a35c76-324f-4128-a166-a4a64f2e721b">
虽然不咋影响使用，但强迫症偶尔看见了也挺难受的，大佬有时间整一下呗

**Comment by wbdosx** [comment]
确实 支持大神翻译  多谢

**Comment by Yukari316** [comment]
最近会看看，之前在忙

**Comment by Yukari316** [comment]
这部分可能是Windows自带的系统组件的文本问题，比如 `旧版的开始菜单`
所对应的注册表项为: `HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced -> Start_ShowClassicMode [DWORD值]`
也就是说这个组件就算不安装EP也能通过修改注册表开启，并不属于EP所提供的组件
我能做的只是汉化EP自身以及EP所提供的系统组件，比如 `sws`
所以暂时无法汉化这部分
